openapi: 3.0.3
info:
  title: Authentication API
  description: Authentication endpoints for user registration, login, and session management
  version: 1.0.0

paths:
  /api/auth/preferences:
    get:
      summary: Get user preferences
      description: Retrieve current user's application preferences
      security:
        - ClerkAuth: []
      responses:
        '200':
          description: User preferences retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'
        '401':
          description: Unauthorized - user not authenticated
        '404':
          description: User preferences not found

    post:
      summary: Create user preferences
      description: Create initial preferences for new user
      security:
        - ClerkAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserPreferences'
      responses:
        '201':
          description: User preferences created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - user not authenticated
        '409':
          description: User preferences already exist

    patch:
      summary: Update user preferences
      description: Update existing user preferences
      security:
        - ClerkAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserPreferences'
      responses:
        '200':
          description: User preferences updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreferences'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - user not authenticated
        '404':
          description: User preferences not found

  /api/auth/session:
    get:
      summary: Get current session info
      description: Retrieve current session information and validation status
      security:
        - ClerkAuth: []
      responses:
        '200':
          description: Session information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfo'
        '401':
          description: No active session

  /api/auth/verification-status:
    get:
      summary: Check email verification status
      description: Check if current user's email is verified
      security:
        - ClerkAuth: []
      responses:
        '200':
          description: Verification status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationStatus'
        '401':
          description: Unauthorized - user not authenticated

components:
  securitySchemes:
    ClerkAuth:
      type: http
      scheme: bearer
      description: Clerk session token

  schemas:
    UserPreferences:
      type: object
      properties:
        id:
          type: string
          description: Unique preference record ID
        clerkUserId:
          type: string
          description: Associated Clerk user ID
        theme:
          type: string
          enum: [light, dark, system]
          description: UI theme preference
        notifications:
          type: boolean
          description: Email notification preference
        lastLoginReminder:
          type: string
          format: date-time
          nullable: true
          description: Last login reminder timestamp
        verificationPrompted:
          type: boolean
          description: Whether user was prompted for email verification
        createdAt:
          type: string
          format: date-time
          description: Record creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Record last update timestamp

    CreateUserPreferences:
      type: object
      properties:
        theme:
          type: string
          enum: [light, dark, system]
          default: system
        notifications:
          type: boolean
          default: true

    UpdateUserPreferences:
      type: object
      properties:
        theme:
          type: string
          enum: [light, dark, system]
        notifications:
          type: boolean
        verificationPrompted:
          type: boolean

    SessionInfo:
      type: object
      properties:
        isActive:
          type: boolean
          description: Whether session is currently active
        expiresAt:
          type: string
          format: date-time
          description: Session expiration time
        lastActiveAt:
          type: string
          format: date-time
          description: Last activity timestamp
        timeUntilExpiry:
          type: integer
          description: Minutes until session expires

    VerificationStatus:
      type: object
      properties:
        isEmailVerified:
          type: boolean
          description: Whether user's email is verified
        canAccessSensitiveFeatures:
          type: boolean
          description: Whether user can access sensitive features
        verificationSentAt:
          type: string
          format: date-time
          nullable: true
          description: When verification email was last sent